Repository Sc0up/scoup-backend, pull requests merged in 2021-11, with the labels that each got.

#196 [Freddie] 그룹 수정 200 -> 204로 변경
  src/main/java/com/postsquad/scoup/web/group/controller/GroupController.java
  src/test/java/com/postsquad/scoup/web/group/GroupAcceptanceTest.java
Labels: fixed🛠

#197 [Freddie] 스케줄 후보의 color code 제거, 스케줄 빌더에서 color code 기본값 처리
  src/main/java/com/postsquad/scoup/web/schedule/domain/Schedule.java
  src/main/java/com/postsquad/scoup/web/schedule/domain/ScheduleCandidate.java
  src/test/java/com/postsquad/scoup/web/schedule/ScheduleCandidateAcceptanceTest.java
Labels: fixed🛠

#206 [Jane] Querydsl 의존성 및 설정 추가
  build.gradle
  src/main/java/com/postsquad/scoup/web/config/QuerydslConfig.java
Labels: chore🍙

#200 [Freddie] Rest Docs 중간점검
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/docs/asciidoc/error-response.adoc
  src/docs/asciidoc/group/group-creation.adoc
  src/docs/asciidoc/group/group-modification.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/schedule/confirmed-schedule-read-all.adoc
  src/docs/asciidoc/schedule/schedule-candidate-read-all.adoc
  src/docs/asciidoc/sign-in/sign-in.adoc
  src/docs/asciidoc/user/email-validation.adoc
  src/docs/asciidoc/user/nickname-validation.adoc
  src/docs/asciidoc/user/sign-up.adoc
  src/main/java/com/postsquad/scoup/web/common/DefaultPostResponse.java
  src/main/java/com/postsquad/scoup/web/config/WebConfig.java
  src/main/java/com/postsquad/scoup/web/group/controller/GroupController.java
  src/main/java/com/postsquad/scoup/web/group/controller/response/GroupValidationResponse.java
  src/main/java/com/postsquad/scoup/web/group/service/GroupService.java
  src/main/java/com/postsquad/scoup/web/schedule/controller/response/ScheduleCandidateReadAllResponse.java
  src/main/java/com/postsquad/scoup/web/schedule/controller/response/ScheduleCandidateReadAllResponses.java
  src/main/java/com/postsquad/scoup/web/user/controller/UserController.java
  src/main/java/com/postsquad/scoup/web/user/controller/request/SignUpRequest.java
  src/main/java/com/postsquad/scoup/web/user/controller/response/EmailValidationResponse.java
  src/main/java/com/postsquad/scoup/web/user/controller/response/NicknameValidationResponse.java
  src/main/java/com/postsquad/scoup/web/user/mapper/UserMapper.java
  src/main/java/com/postsquad/scoup/web/user/service/UserService.java
  src/test/java/com/postsquad/scoup/web/AcceptanceTestBase.java
  src/test/java/com/postsquad/scoup/web/group/GroupAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/schedule/ConfirmedScheduleAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/schedule/ScheduleCandidateAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/signin/SignInAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/user/mapper/UserMapperTest.java
  src/test/java/com/postsquad/scoup/web/user/provider/EmailSignUpProvider.java
  src/test/java/com/postsquad/scoup/web/user/provider/SignUpViaEmailWhenUserAlreadyExistsProvider.java
  src/test/java/com/postsquad/scoup/web/user/provider/SignUpViaSocialWhenUserAlreadyExistsProvider.java
  src/test/java/com/postsquad/scoup/web/user/provider/SignUpWithValidationProvider.java
  src/test/java/com/postsquad/scoup/web/user/provider/SocialSignUpProvider.java
  src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-fields.snippet
Labels: new feature✨

#203 [Jane][4-1-3] 그룹 아이디로 확정 일정 조회
  src/main/java/com/postsquad/scoup/web/schedule/repository/ConfirmedScheduleRepository.java
  src/main/java/com/postsquad/scoup/web/schedule/service/ConfirmedScheduleService.java
  src/test/java/com/postsquad/scoup/web/schedule/ConfirmedScheduleAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/schedule/provider/ConfirmedScheduleReadAllProvider.java
  src/test/java/com/postsquad/scoup/web/schedule/repository/ConfirmedScheduleRepositoryTest.java
Labels: refactor⚙

#201 [Freddie] RequestArugmentsResolver에서 Validation 처리하도록 수정
  src/main/java/com/postsquad/scoup/web/config/RequestParameterArgumentResolver.java
  src/main/java/com/postsquad/scoup/web/config/WebConfig.java
Labels: fixed🛠

#205 [Freddie][4-10-1] 스케줄 후보 조회 시 그룹과 연결
  src/main/java/com/postsquad/scoup/web/schedule/repository/ScheduleCandidateRepository.java
  src/main/java/com/postsquad/scoup/web/schedule/service/ScheduleCandidateService.java
  src/test/java/com/postsquad/scoup/web/schedule/ScheduleCandidateAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/schedule/ScheduleCandidateDatabaseHelper.java
  src/test/java/com/postsquad/scoup/web/schedule/repository/ScheduleCandidateRepositoryTest.java
  src/test/java/com/postsquad/scoup/web/schedule/service/ScheduleCandidateServiceTest.java
Labels: new feature✨

#210 [Freddie] REST Docs로 인해 배포가 되지 않는 문제 수정
  .github/workflows/heroku.yml
  Procfile
  auth-key-properties-creator.sh
  build.gradle
Labels: bug🐛

#211 [Freddie] 마침표 제거
  src/main/java/com/postsquad/scoup/web/auth/exception/OAuthException.java
  src/main/java/com/postsquad/scoup/web/auth/exception/OAuthRequestNotValidException.java
  src/main/java/com/postsquad/scoup/web/auth/exception/OAuthUserNotFoundException.java
  src/main/java/com/postsquad/scoup/web/auth/exception/TokenNotFoundException.java
  src/test/java/com/postsquad/scoup/web/auth/OAuthAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/group/GroupAcceptanceTest.java
Labels: fixed🛠

#212 [Freddie] Mapper 메소드 수정
  src/main/java/com/postsquad/scoup/web/auth/controller/response/KakaoUserResponse.java
  src/main/java/com/postsquad/scoup/web/auth/mapper/SocialAuthenticationResponseMapper.java
  src/main/java/com/postsquad/scoup/web/auth/service/GitHubOAuth.java
  src/main/java/com/postsquad/scoup/web/auth/service/GoogleOAuth.java
  src/main/java/com/postsquad/scoup/web/auth/service/KakaoOAuth.java
  src/main/java/com/postsquad/scoup/web/signin/mapper/SignInResponseMapper.java
  src/main/java/com/postsquad/scoup/web/signin/service/SignInService.java
  src/main/java/com/postsquad/scoup/web/user/mapper/UserMapper.java
Labels: fixed🛠

#214 [Freddie] REST docs에 request parameter 예외 상황 표현
  src/main/java/com/postsquad/scoup/web/user/controller/UserController.java
  src/main/java/com/postsquad/scoup/web/user/controller/request/EmailValidationRequest.java
  src/main/java/com/postsquad/scoup/web/user/controller/request/NicknameValidationRequest.java
  src/main/java/com/postsquad/scoup/web/user/service/UserService.java
  src/test/java/com/postsquad/scoup/web/AcceptanceTestBase.java
  src/test/java/com/postsquad/scoup/web/schedule/ScheduleCandidateAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/user/provider/ValidateEmailRequestParamProvider.java
  src/test/java/com/postsquad/scoup/web/user/provider/ValidateNicknameRequestParamProvider.java
  src/test/java/com/postsquad/scoup/web/user/service/UserServiceTest.java
  src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-parameters.snippet
Labels: new feature✨

#218 [Freddie] 그룹 목업 API 및 REST Docs 문서
  src/docs/asciidoc/group/group-deletion.adoc
  src/docs/asciidoc/group/group-name-validation.adoc
  src/docs/asciidoc/group/group-read-one.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/postsquad/scoup/web/group/controller/GroupController.java
  src/main/java/com/postsquad/scoup/web/group/controller/request/GroupValidationRequest.java
  src/main/java/com/postsquad/scoup/web/group/controller/response/GroupDetailResponse.java
  src/main/java/com/postsquad/scoup/web/group/controller/response/GroupReadOneResponse.java
  src/main/java/com/postsquad/scoup/web/group/controller/response/GroupValidationResponse.java
  src/test/java/com/postsquad/scoup/web/group/GroupAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/group/provider/DeleteGroupProvider.java
Labels: new feature✨

#225 [Freddie] SwaggerConfig 생성 후 관련 설정 이동
  src/main/java/com/postsquad/scoup/ScoupApplication.java
  src/main/java/com/postsquad/scoup/web/config/SwaggerConfig.java
  src/main/java/com/postsquad/scoup/web/config/WebConfig.java
Labels: refactor⚙

#224 [Freddie] 그룹 멤버 목업 API 및 REST Docs 문서
  src/docs/asciidoc/group/group-leave.adoc
  src/docs/asciidoc/group/group-member-creation.adoc
  src/docs/asciidoc/group/group-member-deletion.adoc
  src/docs/asciidoc/group/group-member-modification-role.adoc
  src/docs/asciidoc/group/group-member-read-all.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/postsquad/scoup/web/group/controller/GroupController.java
  src/main/java/com/postsquad/scoup/web/group/controller/GroupMemberController.java
  src/main/java/com/postsquad/scoup/web/group/controller/request/GroupMemberCreationRequest.java
  src/main/java/com/postsquad/scoup/web/group/controller/request/GroupMemberRoleModificationRequest.java
  src/main/java/com/postsquad/scoup/web/group/controller/response/GroupMemberReadAllResponse.java
  src/main/java/com/postsquad/scoup/web/group/controller/response/GroupMemberReadAllResponses.java
  src/main/java/com/postsquad/scoup/web/group/controller/response/GroupMemberResponse.java
  src/main/java/com/postsquad/scoup/web/group/controller/response/GroupMemberResponses.java
  src/test/java/com/postsquad/scoup/web/group/GroupAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/group/GroupMemberAcceptanceTest.java
Labels: new feature✨
