Repository Sc0up/scoup-backend, pull requests merged in 2021-09, with the labels that each got.

#117 [Jane][1-1-2] 소셜 회원가입 기능 구현
  src/main/java/com/postsquad/scoup/web/auth/OAuthType.java
  src/main/java/com/postsquad/scoup/web/user/controller/request/SignUpRequest.java
  src/main/java/com/postsquad/scoup/web/user/domain/OAuthUser.java
  src/main/java/com/postsquad/scoup/web/user/domain/User.java
  src/main/java/com/postsquad/scoup/web/user/mapper/UserMapper.java
  src/main/java/com/postsquad/scoup/web/user/service/UserService.java
  src/test/java/com/postsquad/scoup/web/signin/SignInAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/user/mapper/UserMapperTest.java
Labels: new feature✨

#122 [Jane] UserAcceptanceTest 클래스에서 provider 분리
  src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/user/provider/EmailSignUpProvider.java
  src/test/java/com/postsquad/scoup/web/user/provider/SignUpWhenUserAlreadyExistsProvider.java
  src/test/java/com/postsquad/scoup/web/user/provider/SignUpWithValidationProvider.java
  src/test/java/com/postsquad/scoup/web/user/provider/SocialSignUpProvider.java
  src/test/java/com/postsquad/scoup/web/user/provider/ValidateEmailProvider.java
  src/test/java/com/postsquad/scoup/web/user/provider/ValidateEmailRequestParamProvider.java
  src/test/java/com/postsquad/scoup/web/user/provider/ValidateNicknameProvider.java
  src/test/java/com/postsquad/scoup/web/user/provider/ValidateNicknameRequestParamProvider.java
Labels: refactor⚙

#118 [Freddie][2-2-2] 회원가입 하지 않은 경우 로그인 되지 않도록 수정
  src/main/java/com/postsquad/scoup/web/signin/controller/SignInController.java
  src/main/java/com/postsquad/scoup/web/signin/exception/SignInFailedException.java
  src/main/java/com/postsquad/scoup/web/signin/exception/UserNotFoundException.java
  src/main/java/com/postsquad/scoup/web/signin/service/SignInService.java
  src/test/java/com/postsquad/scoup/web/signin/SignInAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/signin/service/SignInServiceTest.java
Labels: new feature✨

#127 [Jane] Google OAuth Redirect URI 수정
  src/main/resources/auth.properties
Labels: chore🍙

#124 [Jane][1-1-3] 이미 가입한 소셜 서비스로는 중복 가입을 못하도록 방지하는 기능 구현
  src/main/java/com/postsquad/scoup/web/user/domain/OAuthUser.java
  src/main/java/com/postsquad/scoup/web/user/domain/User.java
  src/main/java/com/postsquad/scoup/web/user/repository/UserRepository.java
  src/main/java/com/postsquad/scoup/web/user/service/OAuthUserAlreadyExistsException.java
  src/main/java/com/postsquad/scoup/web/user/service/UserService.java
  src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/user/provider/SignUpViaEmailWhenUserAlreadyExistsProvider.java
  src/test/java/com/postsquad/scoup/web/user/provider/SignUpViaSocialWhenUserAlreadyExistsProvider.java
Labels: new feature✨

#140 [Jane][1-1-1] Github private access token 갱신
  src/main/resources/auth.properties
Labels: chore🍙

#145 [Jane] Database 초기화 로직을 AcceptanceTestBase에 추가
  build.gradle
  src/test/java/com/postsquad/scoup/web/AcceptanceTestBase.java
  src/test/java/com/postsquad/scoup/web/DatabaseCleanup.java
  src/test/java/com/postsquad/scoup/web/group/GroupAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/signin/SignInAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
Labels: new feature✨

#130 [새리][3-2-1] 그룹 수정
  src/main/java/com/postsquad/scoup/web/config/WebConfig.java
  src/main/java/com/postsquad/scoup/web/error/controller/ErrorControllerAdvice.java
  src/main/java/com/postsquad/scoup/web/group/controller/GroupController.java
  src/main/java/com/postsquad/scoup/web/group/controller/request/GroupModificationRequest.java
  src/main/java/com/postsquad/scoup/web/group/domain/Group.java
  src/main/java/com/postsquad/scoup/web/group/exception/GroupNotFoundException.java
  src/main/java/com/postsquad/scoup/web/group/mapper/GroupMapper.java
  src/main/java/com/postsquad/scoup/web/group/service/GroupService.java
  src/main/java/com/postsquad/scoup/web/signin/controller/SignInInterceptor.java
  src/main/java/com/postsquad/scoup/web/signin/exception/AuthorizationFailedException.java
  src/main/java/com/postsquad/scoup/web/signin/exception/UnauthorizedUserException.java
  src/main/java/com/postsquad/scoup/web/signin/exception/UserNotFoundException.java
  src/main/java/com/postsquad/scoup/web/user/LoggedInUser.java
  src/main/java/com/postsquad/scoup/web/user/UserArgumentResolver.java
  src/main/resources/application.properties
  src/test/java/com/postsquad/scoup/web/group/GroupAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/group/mapper/GroupMapperTest.java
  src/test/java/com/postsquad/scoup/web/group/provider/CreateGroupProvider.java
  src/test/java/com/postsquad/scoup/web/group/provider/CreateGroupWithExistingNameProvider.java
  src/test/java/com/postsquad/scoup/web/group/provider/ModifyGroupProvider.java
  src/test/java/com/postsquad/scoup/web/group/provider/ValidateGroupCreationRequestProvider.java
  src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
Labels: new feature✨

#163 [Freddie] query param 처리용 Argument resovler 추가
  src/main/java/com/postsquad/scoup/web/common/ObjectMapperUtils.java
  src/main/java/com/postsquad/scoup/web/config/RequestParameterArgumentResolver.java
  src/main/java/com/postsquad/scoup/web/config/WebConfig.java
  src/test/java/com/postsquad/scoup/web/common/ObjectMapperUtilsTest.java
  src/test/java/com/postsquad/scoup/web/common/RequestDtoForConvertRequestParameterToObjectTest.java
Labels: new feature✨

#176 [Freddie] 테스트, 배포용 프로퍼티 분리
  .github/workflows/gradle-test.yml
  .gitignore
  auth-key-properties-creator.sh
  src/main/java/com/postsquad/scoup/web/config/JasyptConfig.java
  src/main/resources/application-default.properties
  src/main/resources/application-deploy-test.properties
  src/main/resources/application.properties
  src/main/resources/auth/auth.key.deploy.properties
  src/main/resources/auth/auth.properties
Labels: new feature✨

#171 [Freddie][4-10-1] 일정 후보 월별 전체 조회
  src/main/java/com/postsquad/scoup/web/schedule/controller/ScheduleCandidateController.java
  src/main/java/com/postsquad/scoup/web/schedule/controller/request/ScheduleCandidateReadRequest.java
  src/main/java/com/postsquad/scoup/web/schedule/controller/response/ScheduleCandidateReadAllResponse.java
  src/main/java/com/postsquad/scoup/web/schedule/controller/response/ScheduleCandidateReadAllResponses.java
  src/main/java/com/postsquad/scoup/web/schedule/domain/Schedule.java
  src/main/java/com/postsquad/scoup/web/schedule/domain/ScheduleCandidate.java
  src/main/java/com/postsquad/scoup/web/schedule/mapper/ScheduleCandidateReadAllResponseMapper.java
  src/main/java/com/postsquad/scoup/web/schedule/repository/ScheduleCandidateRepository.java
  src/main/java/com/postsquad/scoup/web/schedule/service/ScheduleCandidateService.java
  src/test/java/com/postsquad/scoup/web/schedule/ScheduleCandidateAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/schedule/ScheduleCandidateDatabaseHelper.java
  src/test/java/com/postsquad/scoup/web/schedule/mapper/ScheduleCandidateReadAllResponseMapperTest.java
  src/test/java/com/postsquad/scoup/web/schedule/repository/ScheduleCandidateRepositoryTest.java
  src/test/java/com/postsquad/scoup/web/schedule/service/ScheduleCandidateServiceTest.java
Labels: new feature✨
