Repository Sc0up/scoup-backend, pull requests merged in 2021-08, with the labels that each got.

#3 [프레디] DTO 생성
  src/main/java/com/postsquad/scoup/web/group/controller/GroupTestController.java
  src/main/java/com/postsquad/scoup/web/group/controller/request/GroupBaseRequest.java
  src/main/java/com/postsquad/scoup/web/group/controller/request/GroupCreationRequest.java
  src/main/java/com/postsquad/scoup/web/group/controller/request/GroupModificationRequest.java
  src/main/java/com/postsquad/scoup/web/group/controller/response/GroupBaseResponse.java
  src/main/java/com/postsquad/scoup/web/group/controller/response/GroupDetailResponse.java
  src/main/java/com/postsquad/scoup/web/group/controller/response/GroupMemberResponse.java
  src/main/java/com/postsquad/scoup/web/group/controller/response/GroupMemberResponses.java
  src/main/java/com/postsquad/scoup/web/group/controller/response/GroupResponse.java
  src/main/java/com/postsquad/scoup/web/group/controller/response/GroupResponses.java
  src/main/java/com/postsquad/scoup/web/group/controller/response/GroupValidationResponse.java
  src/main/java/com/postsquad/scoup/web/image/controller/ImageResponse.java
  src/main/java/com/postsquad/scoup/web/schedule/controller/request/ScheduleCandidateRegistrationRequest.java
  src/main/java/com/postsquad/scoup/web/schedule/controller/request/ScheduleConfirmationRequest.java
  src/main/java/com/postsquad/scoup/web/schedule/controller/request/ScheduleModificationRequest.java
  src/main/java/com/postsquad/scoup/web/schedule/controller/request/SchedulePollCancellationRequest.java
  src/main/java/com/postsquad/scoup/web/schedule/controller/request/SchedulePollRequest.java
  src/main/java/com/postsquad/scoup/web/schedule/controller/request/ScheduleRegistrationRequest.java
  src/main/java/com/postsquad/scoup/web/schedule/controller/response/ScheduleBaseResponse.java
  src/main/java/com/postsquad/scoup/web/schedule/controller/response/ScheduleCandidateResponse.java
  src/main/java/com/postsquad/scoup/web/schedule/controller/response/ScheduleCandidateResponses.java
  src/main/java/com/postsquad/scoup/web/schedule/controller/response/ScheduleDetailResponse.java
  src/main/java/com/postsquad/scoup/web/schedule/controller/response/SchedulePollResponse.java
  src/main/java/com/postsquad/scoup/web/schedule/controller/response/ScheduleResponse.java
  src/main/java/com/postsquad/scoup/web/schedule/controller/response/ScheduleResponses.java
  src/main/java/com/postsquad/scoup/web/user/controller/request/SignUpRequest.java
  src/main/java/com/postsquad/scoup/web/user/controller/response/EmailValidationResponse.java
  src/main/java/com/postsquad/scoup/web/user/controller/response/NicknameValidationResponse.java
  src/main/java/com/postsquad/scoup/web/user/controller/response/SignInResponse.java
  src/main/java/com/postsquad/scoup/web/user/controller/response/SocialAuthenticationResponse.java
  src/main/java/com/postsquad/scoup/web/user/controller/response/UserBaseResponse.java
Labels: new feature✨

#17 [Freddie] ErrorResponse 추가
  src/main/java/com/postsquad/scoup/web/error/controller/ErrorControllerAdvice.java
  src/main/java/com/postsquad/scoup/web/error/controller/response/ErrorResponse.java
Labels: new feature✨

#21 [Freddie] 이메일 회원가입
  src/main/java/com/postsquad/scoup/web/user/controller/UserController.java
  src/main/java/com/postsquad/scoup/web/user/controller/request/SignUpRequest.java
  src/main/java/com/postsquad/scoup/web/user/domain/User.java
  src/main/java/com/postsquad/scoup/web/user/domain/UserFactory.java
  src/main/java/com/postsquad/scoup/web/user/repository/UserRepository.java
  src/main/java/com/postsquad/scoup/web/user/service/UserService.java
  src/test/java/com/postsquad/scoup/web/user/controller/UserAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/user/domain/UserFactoryTest.java
  src/test/java/com/postsquad/scoup/web/user/repository/UserRepositoryTest.java
Labels: new feature✨

#24 [Jane] BaseEntity 클래스 추가
  src/main/java/com/postsquad/scoup/ScoupApplication.java
  src/main/java/com/postsquad/scoup/web/common/BaseEntity.java
Labels: new feature✨

#25 [Freddie] AcceptanceTestBase에 RestAssured용 ObjectMapper 설정 추가
  src/test/java/com/postsquad/scoup/web/AcceptanceTestBase.java
  src/test/java/com/postsquad/scoup/web/user/controller/UserAcceptanceTest.java
Labels: new feature✨

#26 [Freddie] UserAcceptanceTest에 BaseEntity 적용
  src/main/java/com/postsquad/scoup/web/user/domain/User.java
  src/test/java/com/postsquad/scoup/web/user/controller/UserAcceptanceTest.java
Labels: refactor⚙

#22 [Jane] 소셜 서비스에 가입된 사용자 정보 요청
  .gitignore
  build.gradle
  src/main/java/com/postsquad/scoup/web/auth/GitHubOAuth.java
  src/main/java/com/postsquad/scoup/web/auth/OAuth.java
  src/main/java/com/postsquad/scoup/web/auth/controller/OAuthController.java
  src/main/java/com/postsquad/scoup/web/auth/exception/AccessTokenNotFoundException.java
  src/main/java/com/postsquad/scoup/web/auth/exception/GitHubUserNotFoundException.java
  src/main/java/com/postsquad/scoup/web/auth/exception/InvalidGitHubRequestException.java
  src/main/java/com/postsquad/scoup/web/auth/exception/OAuthException.java
  src/main/java/com/postsquad/scoup/web/auth/request/AccessTokenRequest.java
  src/main/java/com/postsquad/scoup/web/auth/response/AccessTokenResponse.java
  src/main/java/com/postsquad/scoup/web/auth/response/OAuthUserResponse.java
  src/main/java/com/postsquad/scoup/web/auth/service/OAuthService.java
  src/main/java/com/postsquad/scoup/web/config/JasyptConfig.java
  src/main/java/com/postsquad/scoup/web/config/WebConfig.java
  src/main/java/com/postsquad/scoup/web/image/controller/ImageResponse.java
  src/main/java/com/postsquad/scoup/web/user/controller/response/SocialAuthenticationResponse.java
  src/main/resources/application.properties
  src/main/resources/auth.github.properties
  src/test/java/com/postsquad/scoup/web/auth/OAuthAcceptanceTest.java
Labels: test✔️, new feature✨

#42 User 인수 테스트 Validation 검증 헤더에 로케일 설정
  src/test/java/com/postsquad/scoup/web/user/controller/UserAcceptanceTest.java
Labels: fixed🛠

#28 [새리] 이메일 중복확인
  src/main/java/com/postsquad/scoup/web/error/controller/ErrorControllerAdvice.java
  src/main/java/com/postsquad/scoup/web/error/controller/response/ErrorResponse.java
  src/main/java/com/postsquad/scoup/web/user/controller/UserController.java
  src/main/java/com/postsquad/scoup/web/user/controller/response/EmailValidationResponse.java
  src/main/java/com/postsquad/scoup/web/user/repository/UserRepository.java
  src/main/java/com/postsquad/scoup/web/user/service/UserService.java
  src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/user/service/UserServiceTest.java
Labels: new feature✨

#31 [Freddie] .gitignore에 generated 추가
  .gitignore
Labels: chore🍙

#35 [Freddie] ErrorControllerAdvice에서 메세지를 좀 더 구체적으로 반환하도록 수정
  src/main/java/com/postsquad/scoup/web/error/controller/ErrorControllerAdvice.java
  src/main/java/com/postsquad/scoup/web/error/controller/response/ErrorResponse.java
  src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
Labels: fixed🛠

#57 [Freddie] Error response message 반영 및 테스트 케이스 수정
  src/main/java/com/postsquad/scoup/web/error/controller/ErrorControllerAdvice.java
  src/main/java/com/postsquad/scoup/web/error/controller/response/ErrorResponse.java
  src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
Labels: fixed🛠

#32 [Freddie] Mapstruct 추가 및 User에 적용
  build.gradle
  src/main/java/com/postsquad/scoup/web/config/WebConfig.java
  src/main/java/com/postsquad/scoup/web/user/domain/UserFactory.java
  src/main/java/com/postsquad/scoup/web/user/mapper/UserMapper.java
  src/main/java/com/postsquad/scoup/web/user/service/UserService.java
  src/test/java/com/postsquad/scoup/web/user/mapper/UserMapperTest.java
Labels: new feature✨

#36 [Freddie] AcceptanceTestBase에 공통으로 사용할 ignoringFields 추가
  src/test/java/com/postsquad/scoup/web/AcceptanceTestBase.java
  src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
Labels: chore🍙

#44 [Freddie] 이미 가입한 이메일로 가입 시 실패 메세지 전달
  src/main/java/com/postsquad/scoup/web/error/controller/response/ErrorResponse.java
  src/main/java/com/postsquad/scoup/web/user/controller/UserController.java
  src/main/java/com/postsquad/scoup/web/user/service/SignUpFailedException.java
  src/main/java/com/postsquad/scoup/web/user/service/UserAlreadyExistsException.java
  src/main/java/com/postsquad/scoup/web/user/service/UserService.java
  src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
Labels: new feature✨

#39 [Jane] ErrorControllerAdvice에 OAuth 관련 예외를 처리하는 핸들러 추가
  src/main/java/com/postsquad/scoup/web/auth/GitHubOAuth.java
  src/main/java/com/postsquad/scoup/web/auth/controller/OAuthController.java
  src/main/java/com/postsquad/scoup/web/auth/exception/GitHubRequestNotValidException.java
  src/main/java/com/postsquad/scoup/web/auth/exception/InvalidGitHubRequestException.java
  src/main/java/com/postsquad/scoup/web/auth/exception/OAuthException.java
  src/test/java/com/postsquad/scoup/web/auth/controller/OAuthAcceptanceTest.java
Labels: new feature✨, refactor⚙

#60 [Freddie] indentation 수정
  src/main/java/com/postsquad/scoup/web/auth/GitHubOAuth.java
  src/main/java/com/postsquad/scoup/web/auth/controller/OAuthController.java
  src/main/java/com/postsquad/scoup/web/auth/request/AccessTokenRequest.java
  src/main/java/com/postsquad/scoup/web/auth/service/OAuthService.java
  src/main/java/com/postsquad/scoup/web/config/JasyptConfig.java
  src/main/java/com/postsquad/scoup/web/config/WebConfig.java
  src/main/java/com/postsquad/scoup/web/error/controller/response/ErrorResponse.java
  src/main/java/com/postsquad/scoup/web/group/controller/response/GroupValidationResponse.java
  src/main/java/com/postsquad/scoup/web/user/controller/UserController.java
  src/main/java/com/postsquad/scoup/web/user/controller/request/SignUpRequest.java
  src/main/java/com/postsquad/scoup/web/user/controller/response/EmailValidationResponse.java
  src/main/java/com/postsquad/scoup/web/user/controller/response/SocialAuthenticationResponse.java
  src/main/java/com/postsquad/scoup/web/user/domain/User.java
  src/main/java/com/postsquad/scoup/web/user/service/UserService.java
  src/main/resources/application.properties
  src/test/java/com/postsquad/scoup/web/AcceptanceTestBase.java
  src/test/java/com/postsquad/scoup/web/auth/controller/OAuthAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/user/mapper/UserMapperTest.java
  src/test/java/com/postsquad/scoup/web/user/repository/UserRepositoryTest.java
  src/test/java/com/postsquad/scoup/web/user/service/UserServiceTest.java
Labels: refactor⚙, chore🍙

#61 [Freddie] User api에 users 추가
  src/main/java/com/postsquad/scoup/web/user/controller/UserController.java
  src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
Labels: fixed🛠

#62 [Jane] [1-1-1] GitHub 요청이 유효한지 검증하는 실패 테스트 추가
  src/main/java/com/postsquad/scoup/web/auth/GitHubOAuth.java
  src/main/java/com/postsquad/scoup/web/auth/OAuth.java
  src/main/java/com/postsquad/scoup/web/auth/controller/OAuthController.java
  src/main/java/com/postsquad/scoup/web/auth/controller/request/AccessTokenRequest.java
  src/main/java/com/postsquad/scoup/web/auth/controller/response/AccessTokenResponse.java
  src/main/java/com/postsquad/scoup/web/auth/controller/response/OAuthUserResponse.java
  src/main/java/com/postsquad/scoup/web/auth/controller/response/SocialAuthenticationResponse.java
  src/main/java/com/postsquad/scoup/web/auth/exception/GitHubRequestNotValidException.java
  src/main/java/com/postsquad/scoup/web/auth/service/OAuthService.java
  src/test/java/com/postsquad/scoup/web/auth/OAuthAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/auth/controller/OAuthAcceptanceTest.java
Labels: test✔️

#69 [새리][1-3-2] 닉네임 중복확인
  src/main/java/com/postsquad/scoup/web/user/controller/UserController.java
  src/main/java/com/postsquad/scoup/web/user/controller/response/NicknameValidationResponse.java
  src/main/java/com/postsquad/scoup/web/user/repository/UserRepository.java
  src/main/java/com/postsquad/scoup/web/user/service/UserService.java
  src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
Labels: new feature✨

#71 [Freddie][1-2-3] 회원가입 시 닉네임 이미 존재하면 회원가입 실패
  src/main/java/com/postsquad/scoup/web/user/repository/UserRepository.java
  src/main/java/com/postsquad/scoup/web/user/service/NicknameAlreadyExistsException.java
  src/main/java/com/postsquad/scoup/web/user/service/UserAlreadyExistsException.java
  src/main/java/com/postsquad/scoup/web/user/service/UserService.java
  src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
Labels: new feature✨

#77 [새리] 이메일 중복 검사 인수테스트 네이밍 변경
  src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
Labels: refactor⚙

#74 [Freddie] 이메일로 회원가입 리팩토링
  src/main/java/com/postsquad/scoup/web/user/repository/UserRepository.java
  src/main/java/com/postsquad/scoup/web/user/service/EmailAlreadyExistsException.java
  src/main/java/com/postsquad/scoup/web/user/service/UserAlreadyExistsException.java
  src/main/java/com/postsquad/scoup/web/user/service/UserService.java
  src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/user/service/UserServiceTest.java
Labels: refactor⚙

#75 [새리][3-1-1] 그룹 생성
  src/main/java/com/postsquad/scoup/web/group/controller/GroupController.java
  src/main/java/com/postsquad/scoup/web/group/controller/request/GroupBaseRequest.java
  src/main/java/com/postsquad/scoup/web/group/controller/request/GroupCreationRequest.java
  src/main/java/com/postsquad/scoup/web/group/domain/Group.java
  src/main/java/com/postsquad/scoup/web/group/mapper/GroupMapper.java
  src/main/java/com/postsquad/scoup/web/group/repository/GroupRepository.java
  src/main/java/com/postsquad/scoup/web/group/service/GroupService.java
  src/main/resources/application.properties
  src/test/java/com/postsquad/scoup/web/group/GroupAcceptanceTest.java
  src/test/java/com/postsquad/scoup/web/group/mapper/GroupMapperTest.java
  src/test/java/com/postsquad/scoup/web/group/repository/GroupRepositoryTest.java
Labels: new feature✨

#79 [Freddie] nimbus jose jwt 의존성 추가
  build.gradle
Labels: chore🍙
